image: python:3.8-alpine

stages:
  - test
  - pre_commit
  - build
  - deploy

variables:
  DOCKER_HUB_REPO: "shodaisd/oxygencs-app-grp2-eq8"
  IMAGE_TAG: "latest"

before_script:
  - apk add --no-cache git
  - apk update
  - apk add --no-cache build-base libffi-dev postgresql-dev
  - pip install pipenv

pre_commit:
  stage: pre_commit
  variables:
    HOST: http://159.203.50.162
    TOKEN: d6e33ac9ad141a18af77
    T_MAX: 20
    T_MIN: 10
    DATABASE_URL: postgresql://user02eq8:5ZBBwc9GvESZLKhg@157.230.69.113:5432/db02eq8
  script:
    - pipenv install --dev
    - pipenv install --dev pre-commit
    - pipenv run pre-commit run --all-files

unit_tests:
  stage: test
  variables:
    HOST: http://159.203.50.162
    TOKEN: d6e33ac9ad141a18af77
    T_MAX: 20
    T_MIN: 10
    DATABASE_URL: postgresql://user02eq8:5ZBBwc9GvESZLKhg@157.230.69.113:5432/db02eq8
  script:
    - pipenv install --dev
    - pipenv run pytest

build_docker_image:
  stage: build
  only:
    - main
  script:
    - docker build -t $DOCKER_HUB_REPO:$IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $DOCKER_HUB_REPO:$IMAGE_TAG

deploy_to_dockerhub:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to Docker Hub..."
