image: python:3.8-alpine

stages:
  - test
  - pre_commit
  - build
  - deploy

variables:
  DOCKER_IMAGE_TAG: "latest"
  DOCKER_REGISTRY_URL: "registry.gitlab.com"
  DOCKER_IMAGE_NAME: "shodaisd/oxygencs-app-grp2-eq8"

before_script:
  - apk add --no-cache git
  - apk update
  - apk add --no-cache build-base libffi-dev postgresql-dev
  - pip install pipenv
  - apk add --no-cache docker

pre_commit:
  stage: pre_commit
  variables:
    HOST: http://159.203.50.162
    TOKEN: d6e33ac9ad141a18af77
    T_MAX: 20
    T_MIN: 10
    DATABASE_URL: postgresql://user02eq8:5ZBBwc9GvESZLKhg@157.230.69.113:5432/db02eq8
  script:
    - pipenv install --dev
    - pipenv install --dev pre-commit
    - pipenv run pre-commit run --all-files

unit_tests:
  stage: test
  variables:
    HOST: http://159.203.50.162
    TOKEN: d6e33ac9ad141a18af77
    T_MAX: 20
    T_MIN: 10
    DATABASE_URL: postgresql://user02eq8:5ZBBwc9GvESZLKhg@157.230.69.113:5432/db02eq8
  script:
    - pipenv install --dev
    - pipenv run pytest

build_image:
  stage: build
  only:
    - main
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login registry.gitlab.com -u Shodaisd  -p sok36Qok*
  script:
    - docker build -t registry.gitlab.com/log680/oxygencs-grp2-eq8 .
    - docker push registry.gitlab.com/log680/oxygencs-grp2-eq8

deploy_to_Kubernetes:
  stage: deploy
  only:
    - main
  script:
    - echo "$KUBECONFIG_CONTENT" > kubeconfig.yaml
    - export KUBECONFIG=$(pwd)/kubeconfig.yaml
    - kubectl --kubeconfig=kubeconfig.yaml delete deployment oxygenscs-grp2-eq8
    - kubectl --kubeconfig=kubeconfig.yaml apply -f config/deployment-HVAC.yaml
